language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=pypy

install:
  - pip install tox
script:
  - tox

matrix:
  allow_failures:
    - env: TOXENV=pypy
