language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: pypy
      env: TOXENV=pypy
    - python: pypy3
      env: TOXENV=pypy3

  allow_failures:
    - env: TOXENV=pypy
    - env: TOXENV=pypy3

install:
  - pip install tox
script:
  - tox
